### ISSUE TITLE
Support multiple test environment in Travis CI

### ISSUE THREAD

**Issue by TonyPythoneer** [StreetVoice/django-celery-ses#5]
There is a `.travis.yml` can be referred: https://github.com/vinta/django-email-confirm-la/blob/master/.travis.yml

Travis CI will build different test environments to run this repo.

```yml
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO="django>=1.5,<1.6"
  - DJANGO="django>=1.6,<1.7"
  - DJANGO="django>=1.7,<1.8"
  - DJANGO="django>=1.8,<1.9"
  - DJANGO="django>=1.9,<1.10"
```
